import { Product } from './Product';

export const PRODUCTS: Product[] = [
  {
    id: 0,
    imageUrl: "https://m.media-amazon.com/images/I/715THGjmXaL._SL1500_.jpg",
    field: "Skin",
    name: "Smoothing Face Mask",
    manufacturer: "Alder New York",
    ingredients: [
      "BENZYL ALCOHOL",
      "TOCOPHERYL ACETATE",
      "WATER",
      "KAOLIN",
      "HYDROXYPROPYL STARCH PHOSPHATE",
      "ASCOPHYLLUM NODOSUM (KNOTTED WRACK) EXTRACT",
      "GLYCERIN",
      "ACTIVATED CHARCOAL",
      "SODIUM HYALURONATE",
      "DEHYDROACETIC ACID",
    ],
    bad_ones: ["BENZYL ALCOHOL"],
  },
  {
    id: 1,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/586160/original.",
    field: "Skin",
    name: "Brighten + Renew Facial Mask, Hydrating Watermelon",
    manufacturer: "Spalife",
    ingredients: [
      "RETINYL PALMITATE",
      "FRAGRANCE",
      "PHENOXYETHANOL",
      "TOCOPHERYL ACETATE",
      "POLYSORBATE-80",
      "CHLORPHENESIN",
      "GLYCERIN",
      "PROPANEDIOL",
      "WATER",
      "METHYLPROPANEDIOL",
      "CITRULLUS VULGARIS (WATERMELON) FRUIT EXTRACT",
      "HYDROLYZED COLLAGEN",
      "PORTULACA OLERACEA (GREEN PURSLANE) EXTRACT",
      "ALOE BARBADENSIS (ALOE VERA) LEAF EXTRACT",
      "ALTHAEA ROSEA ROOT EXTRACT",
      "BETA-GLUCAN",
      "TOCOPHEROL",
      "ASCORBIC ACID (VITAMIN C)",
      "DISODIUM EDTA",
      "XANTHAN GUM",
      "1,2-HEXANEDIOL",
      "CAPRYLYL GLYCOL",
      "ILLICIUM VERUM (ANISE) FRUIT EXTRACT",
    ],
    bad_ones: [
      "RETINYL PALMITATE",
      "FRAGRANCE",
      "PHENOXYETHANOL",
      "TOCOPHERYL ACETATE",
      "POLYSORBATE-80",
      "CHLORPHENESIN",
    ],
  },
  {
    id: 2,
    imageUrl:
      "https://images.ulta.com/is/image/Ulta/2552028?op_sharpen=1&resMode=bilin&qlt=85&wid=800&hei=800&fmt=jpg",
    field: "Hair",
    name: "Moroccan Rhassoul 5-in-1 Clay Treatment",
    manufacturer: "Naturalicious",
    ingredients: [
      "PHENOXYETHANOL",
      "POLYSORBATE-60",
      "GLYCERIN",
      "MOROCCAN LAVA CLAY",
      "WATER",
      "ALOE BARBADENSIS (ALOE VERA) LEAF JUICE",
      "CETEARYL ALCOHOL",
      "THEOBROMA CACAO (COCOA) SEED BUTTER",
      "VITIS VINIFERA (GRAPE) SEED OIL",
      "PERSEA GRATISSIMA (AVOCADO) OIL",
    ],
    bad_ones: ["PHENOXYETHANOL", "POLYSORBATE-60"],
  },
  {
    id: 3,
    imageUrl: "https://m.media-amazon.com/images/I/61N9-x2eN1L._AC_SX425_.jpg",
    field: "Hair",
    name: "Everyday Coconut Volumizing Sea Salt Texture Spray for Hair",
    manufacturer: "Alaffia",
    ingredients: [
      "PHENOXYETHANOL",
      "GLYCERIN",
      "POTASSIUM SORBATE",
      "AZADIRACHTIN INDICA (NEEM) POWDER",
      "COCOS NUCIFERA (COCONUT) WATER",
      "SODIUM CHLORIDE",
      "COCOS NUCIFERA FRUIT EXTRACT",
      "XANTHAN GUM",
      "ASCORBIC ACID (VITAMIN C)",
    ],
    bad_ones: ["PHENOXYETHANOL"],
  },
  {
    id: 4,
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0277/3237/7738/products/kapanuinailsedited13_2250x.png?v=1600145377",
    field: "Nails",
    name: "Base and Top Coat Sealer",
    manufacturer: "Kapa Nui",
    ingredients: ["PROPYLENE GLYCOL METHYL ETHER"],
    bad_ones: ["PROPYLENE GLYCOL METHYL ETHER"],
  },
  {
    id: 5,
    imageUrl:
      "http://static1.squarespace.com/static/5c60551ba09a7e2bba52a925/5c606266fa0d60425ba52b7d/5c61a5a5fa0d604b1e7f08fd/1570715059587/?format=1500w",
    field: "Nails",
    name: "100% Pure Acetone Nail Polish Remover",
    manufacturer: "ONYX Professionals",
    ingredients: ["ACETONE", "DENATONIUM BENZOATE"],
    bad_ones: ["ACETONE"],
  },
  {
    id: 6,
    imageUrl:
      "https://www.rejuvaminerals.com/store/media/Sand-high-res-Compressed.jpg",
    field: "Makeup",
    name: "Natural Look Pressed Foundation, Sand",
    manufacturer: "Rejuva Minerals",
    ingredients: [
      " IRON OXIDES",
      "BORON NITRIDE",
      "TAPIOCA STARCH",
      "LAUROYL LYSINE",
      "COPERNICIA CERIFERA (CARNAUBA) WAX",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "CAPRYLYL GLYCOL",
      "VITIS VINIFERA (GRAPE) SEED OIL",
      "VACCINIUM MACROCARPON (CRANBERRY) SEED OIL",
      "ROSMARINUS OFFICINALIS (ROSEMARY) LEAF OIL",
    ],
    bad_ones: [],
  },
  {
    id: 7,
    imageUrl:
      "https://www.maiasminerals.com/v/vspfiles/photos/EYELINERK-2T.jpg",
    field: "Makeup",
    name: "Mineral Eyeliner, Kohl",
    manufacturer: "Maia's Mineral Galaxy",
    ingredients: [
      "ROSMARINUS OFFICINALIS (ROSEMARY) EXTRACT",
      "MICA",
      "CI 77499",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL",
      "THEOBROMA CACAO (COCOA) SEED BUTTER",
      "EUPHORBIA CERIFERA (CANDELILLA) WAX",
      "COPERNICIA CERIFERA (CARNAUBA) WAX",
      "BUTYROSPERMUM PARKII (SHEA) BUTTER",
      "TOCOPHEROL",
    ],
    bad_ones: [],
  },
  {
    id: 8,
    imageUrl: "https://static.ewg.org/skindeep_images/8993/899338.jpg",
    field: "After Sun Product",
    name: "Olita After Sun Body Serum, Soothing Citrus",
    manufacturer: "Olita",
    ingredients: [
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "TOCOPHERYL ACETATE",
      "COCOS NUCIFERA (COCONUT) OIL",
      "CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL",
      "ALOE BARBADENSIS (ALOE VERA) OIL",
      "PRUNUS ARMENIACA (APRICOT) OIL",
      "VITIS VINIFERA (GRAPE) SEED OIL",
      "ISOPROPYL MYRISTATE",
      "CAPRYLIC/ CAPRIC TRIGLYCERIDE",
      "CITRUS PARADISI (GRAPEFRUIT) PEEL OIL",
    ],
    bad_ones: [],
  },
  {
    id: 9,
    imageUrl:
      "https://phorcys-static.ewg.org/image/contents/598730/original.jpg",
    field: "After Sun Product",
    name: "Paul Penders Herbal After-Sun Lotion",
    manufacturer: "Paul Penders",
    ingredients: [
      "MENTHA PIPERITA (PEPPERMINT) LEAF",
      "PELAGONIUM GRAVEOLENS OIL",
      "TOCOPHERYL ACETATE",
      "LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL",
      "CHAMOMILLA RECUTITA (CHAMOMILE) FLOWER POWDER",
      "WATER",
      "COCOS NUCIFERA FRUIT EXTRACT",
      "GLYCERIN",
      "CETEARYL OLIVATE",
      "SORBITAN OLIVATE",
    ],
    bad_ones: [],
  },
  {
    id: 10,
    imageUrl:
      "https://phorcys-static.ewg.org/image/contents/500152/medium.png?1551501720",
    field: "Sunless Tanning",
    name: "Tropic Sun Drops Gradual Tanning Facial Serum",
    manufacturer: "Tropic",
    ingredients: [
      "PROPANEDIOL",
      "GLYCERIN",
      "PHYTIC ACID",
      "ALOE BARBADENSIS (ALOE VERA) LEAF JUICE",
      "DIHYDROXYACETONE",
      "CARAMEL COLOR",
      "MELANIN",
      "PASSIONFLOWER FRUIT EXTRACT",
      "XANTHAN GUM",
      "COCOS NUCIFERA (COCONUT) WATER",
      "LEVULINIC ACID",
      "SODIUM ANISATE",
      "SODIUM LEVULINATE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 11,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/566187/original.",
    field: "Sunless Tanning",
    name: "Bali Body Face Tan Water",
    manufacturer: "Bali Body",
    ingredients: [
      "BENZYL ALCOHOL",
      "SODIUM METABISULFITE",
      "PHENOXYETHANOL",
      "POLYSORBATE-20",
      "ROSA DAMASCENA FLOWER EXTRACT",
      "GLYCERIN",
      "CITRIC ACID",
      "ETHYLHEXYLGLYCERIN",
      "WATER",
      "DIHYDROXYACETONE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 12,
    imageUrl:
      "https://phorcys-static.ewg.org/kwikee_2019/kwikeeBasket-2019-05-17T20-43-03.000Z/011111553460_CF__JPEG_3.jpg",
    field: "Bar Soap",
    name: "Dove Dry Oil Beauty Bar",
    manufacturer: "Dove",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140)",
      "COCAMIDOPROPYL BETAINE",
      "FD&C YELLOW NO. 6 (CI 15985)",
      "PROPYLENE GLYCOL",
      "TETRASODIUM ETIDRONATE",
      "TETRASODIUM EDTA",
      "SODIUM LAUROYL ISETHIONATE",
      "STEARIC ACID",
      "LAURIC ACID",
      "SODIUM TALLOWATE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 13,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/590885/original.",
    field: "Bar Soap",
    name: "Caswell Massey Triple Milled Soaps, Centuries Almond",
    manufacturer: "Caswell Massey",
    ingredients: [
      "SODIUM BORATE",
      "GLYCERIN",
      "TETRASODIUM ETIDRONATE",
      "SODIUM PALMATE",
      "SODIUM COCOATE",
      "SODIUM PALM KERNELATE",
      "WATER",
      "ALOE BARBADENSIS (ALOE VERA) LEAF JUICE",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL",
      "SODIUM CHLORIDE",
    ],
    bad_ones: ["FRAGRANCE", "METHYLISOTHIAZOLINONE"],
  },
  {
    id: 14,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/584485/original.",
    field: "Hand Sanitizer",
    name: "Find Your Happy Place Hand Sanitizer, Chamomile & Sandalwood",
    manufacturer: "Find Your Happy Place",
    ingredients: [
      "CI 42090 (FD&C BLUE NO. 1 OR D&C BLUE NO. 4)",
      "AMINOMETHYL PROPANOL",
      "TOCOPHERYL ACETATE",
      "GLYCERIN",
      "ISOPROPYL ALCOHOL",
      "WATER",
      "BUTYLENE GLYCOL",
      "CARBOMER",
      "ISOPROPYL MYRISTATE",
      "THEOBROMA CACAO (COCOA) SEED BUTTER",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 15,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/584905/original.",
    field: "Hand Sanitizer",
    name: "Wet Ones, Hand Sanitizer, Fresh",
    manufacturer: "Wet Ones",
    ingredients: [
      "PROPYLENE GLYCOL",
      "AMINOMETHYL PROPANOL",
      "TOCOPHERYL ACETATE",
      "GLYCERIN",
      "RICINUS COMMUNIS (CASTOR) SEED OIL",
      "WATER",
      "PANTHENOL",
      "ACRYLATES/ C10-30 ALKYL ACRYLATE CROSSPOLYMER",
      "ISOPROPYL MYRISTATE",
      "PEG-40 HYDROGENATED CASTOR OIL",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 16,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/601331/original.",
    field: "Liquid Soap",
    name: "Raw Sugar Hand Wash Therapy, Geranium + Sweet Orange Oil",
    manufacturer: "Raw Sugar",
    ingredients: [
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "COCAMIDOPROPYL BETAINE",
      "PELARGONIUM GRAVEOLENS (GERANIUM) FLOWER OIL",
      "POLYQUATERNIUM-7",
      "PHENOXYETHANOL",
      "PEG-150 DISTEARATE",
      "SODIUM BENZOATE",
      "SODIUM C14-16 OLEFIN SULFONATE",
      "GLYCERIN",
      "DISODIUM LAURETH SULFOSUCCINATE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 17,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/566460/original.",
    field: "Liquid Soap",
    name: "Softsoap Hand Soap, Clean Splash",
    manufacturer: "Softsoap",
    ingredients: [
      "COCAMIDOPROPYL BETAINE",
      "POLYQUATERNIUM-7",
      "SODIUM LAURETH SULFATE",
      "SODIUM BENZOATE",
      "PEG-18 GLYCERYL OLEATE/ COCOATE",
      "CITRIC ACID",
      "TETRASODIUM EDTA",
      "POLOXAMER 124",
      "D&C ORANGE NO. 4 (CI 15510)",
      "WATER",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 18,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/541995/original.",
    field: "Facial Clenser",
    name: "artNaturals Tea Tree Face Wash",
    manufacturer: "artNaturals",
    ingredients: [
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "POTASSIUM HYDROXIDE",
      "CHLORPHENESIN",
      "ETHYLHEXYLGLYCERIN",
      "WATER",
      "PALMITIC ACID",
      "STEARIC ACID",
      "MYRISTIC ACID",
      "LAURIC ACID",
      "SODIUM METHYL COCOYL TAURATE",
    ],
    bad_ones: [],
  },
  {
    id: 19,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/607645/original.",
    field: "Facial Clenser",
    name: "Hustle Clean Face Wipes, Unscented",
    manufacturer: "Hustle Clean",
    ingredients: [
      "CITRUS GRANDIS (GRAPEFRUIT) SEED EXTRACT",
      "SODIUM HYDROXIDE",
      "PHENOXYETHANOL",
      "ISOCETETH-20",
      "SALICYLIC ACID",
      "SODIUM BENZOATE",
      "PROPANEDIOL",
      "GLYCERIN",
      "CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT",
      "DECYL GLUCOSIDE",
    ],
    bad_ones: [],
  },
  {
    id: 20,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/607523/original.",
    field: "Shampoo",
    name: "Hask Purifying Shampoo",
    manufacturer: "Hask",
    ingredients: [
      "CITRUS LIMON (LEMON) PEEL OIL",
      "METHYLCHLOROISOTHIAZOLINONE",
      "COCAMIDOPROPYL BETAINE",
      "SODIUM HYDROXIDE",
      "PHENOXYETHANOL",
      "CYCLOPENTASILOXANE",
      "SULISOBENZONE",
      "SODIUM C14-16 OLEFIN SULFONATE",
      "ACRYLATES COPOLYMER",
      "GLYCERIN",
    ],
    bad_ones: ["FRAGRANCE", "METHYLISOTHIAZOLINONE"],
  },
  {
    id: 21,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/567320/original.",
    field: "Shampoo",
    name: "Garnier Fructis Full & Plush Fortifying Shampoo",
    manufacturer: "Garnier",
    ingredients: [
      "TRIETHANOLAMINE",
      "BENZYL ALCOHOL",
      "CITRUS LIMON (LEMON) PEEL EXTRACT",
      "SODIUM HYDROXIDE",
      "PHENOXYETHANOL",
      "AMYLCINNAMALDEHYDE",
      "SODIUM LAURETH SULFATE",
      "SODIUM BENZOATE",
      "SALICYLIC ACID",
      "LINALOOL",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 22,
    imageUrl: "https://static.ewg.org/skindeep_images/8601/860102.jpg",
    field: "Conditioner",
    name: "Pantene Daily Moisture Renewal Pro-V Daily Moisture Renewal Conditioner",
    manufacturer: "Pantene",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140)",
      "BENZYL ALCOHOL",
      "METHYLCHLOROISOTHIAZOLINONE",
      "BEHENTRIMONIUM METHOSULFATE",
      "DICETYLDIMONIUM CHLORIDE",
      "CITRIC ACID",
      "WATER",
      "STEARYL ALCOHOL",
      "AMINOPROPYL DIMETHICONE",
      "CETYL ALCOHOL",
    ],
    bad_ones: ["FRAGRANCE", "METHYLISOTHIAZOLINONE"],
  },
  {
    id: 23,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/567309/original.",
    field: "Conditioner",
    name: "Garnier Fructis Damage Eraser Fortifying Conditioner",
    manufacturer: "Ganrier",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140)",
      "LIMONENE",
      "BENZYL ALCOHOL",
      "BENZYL SALICYLATE",
      "POTASSIUM HYDROXIDE",
      "CITRUS LIMON (LEMON) PEEL EXTRACT",
      "BEHENTRIMONIUM METHOSULFATE",
      "BEHENTRIMONIUM CHLORIDE",
      "FD&C YELLOW NO. 6 (CI 15985)",
      "PHENOXYETHANOL",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 24,
    imageUrl: "https://phorcys-static.ewg.org/kwikee/017/000/205/649.jpg",
    field: "Hair Spray",
    name: "Got2 B Flex Hold Hairspray",
    manufacturer: "Got2 B",
    ingredients: [
      "DECAMETHYLCYCLOPENTASILOXANE",
      "AMINOMETHYL PROPANOL",
      "BENZOIC ACID",
      "ALCOHOL DENATURED",
      "HYDROFLUOROCARBON 152A",
      "OCTYLACRYLAMIDE/ ACRYLATES/ BUTYLAMINOETHYL/ METHACRYLATE COPOLYMER",
      "WATER",
      "TRIETHYL CITRATE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 25,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/604778/original.",
    field: "Hair Spray",
    name: "Dove Refresh + Care Dry Shampoo",
    manufacturer: "Dove",
    ingredients: [
      "ISOBUTANE",
      "BUTANE",
      "PROPANE",
      "SD ALCOHOL 40B",
      "CYCLOPENTASILOXANE",
      "ALUMINUM STARCH OCTENYLSUCCINATE",
      "SILICA, AMORPHOUS",
      "ISOPROPYL MYRISTATE",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 26,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/593415/original.",
    field: "Nail Polish",
    name: "10Free Clean Nail Color, Aloha Beaches!",
    manufacturer: "10Free",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140) LAKE",
      "D&C YELLOW NO. 11 (CI 47000)",
      "D&C RED NO. 30 (CI73360) LAKE",
      "D&C RED NO. 33 (CI 17200) LAKE",
      "CI 15850 (D&C RED NO. 6 OR 7) LAKE",
      "CI 15850 (D&C RED NO. 6 OR 7) LAKE",
      "EXT. D&C VIOLET NO. 2 (CI 60730)",
      "ISOPROPYL ALCOHOL",
      "GLYCERIN",
      "SUCROSE ACETATE ISOBUTYRATE",
    ],
    bad_ones: ["CI 42090 (FD&C BLUE NO. 1 OR D&C BLUE NO. 4) ALUMINUM LAKE"],
  },
  {
    id: 27,
    imageUrl: "https://static.ewg.org/skindeep_images/9204/920442.jpg",
    field: "Nail Polish",
    name: "Lauren B. Beauty Nail Couture, Mandeville Maven",
    manufacturer: "Lauren B. Beauty Nail Couture",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140) LAKE",
      "BUTYL ALCOHOL",
      "BENZOPHENONE-1",
      "ISOPROPYL ALCOHOL",
      "ACRYLATES COPOLYMER",
      "ALUMINA",
      "CI 77499",
      "BUTYL ACETATE",
      "ETHYL ACETATE",
      "NITROCELLULOSE",
    ],
    bad_ones: [],
  },
  {
    id: 28,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/583584/original.",
    field: "Polish Remover",
    name: "Equate Advanced Nail Polish Remover, Lavender",
    manufacturer: "Equate",
    ingredients: [
      "BENZOPHENONE-1",
      "ACETONE",
      "EXT. D&C VIOLET NO. 2 (CI 60730)",
      "WATER",
      "PERSEA GRATISSIMA (AVOCADO) OIL",
      "OLEA EUROPAEA (OLIVE) OIL",
      "COCOS NUCIFERA (COCONUT) OIL",
      "LAVANDULA HYBRIDA OIL",
      "DENATONIUM BENZOATE",
      "D&C RED NO. 33 (CI 17200)",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 29,
    imageUrl: "https://static.ewg.org/skindeep_images/9206/920672.jpg",
    field: "Polish Remover",
    name: "tenoverten Rose Polish Remover",
    manufacturer: "tenoverten",
    ingredients: [
      "PHENOXYETHANOL",
      "POLYSORBATE-20",
      "ROSA CANINA (DOG ROSE) FRUIT EXTRACT",
      "SODIUM BENZOATE",
      "GLYCERIN",
      "POTASSIUM SORBATE",
      "PROPYLENE CARBONATE",
      "WATER",
      "ALOE BARBADENSIS (ALOE VERA) LEAF JUICE",
      "EQUISETUM ARVENSE (HORSETAIL) EXTRACT",
    ],
    bad_ones: ["FRAGRANCE"],
  },
  {
    id: 30,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/555545/original.",
    field: "Foundation",
    name: "Revlon Age Defying Powder, Light Medium",
    manufacturer: "Revlon",
    ingredients: [
      "TALC",
      "METHYLPARABEN",
      "METHYLPARABEN",
      "ZINC STEARATE",
      "LECITHIN",
      "SORBIC ACID",
      "CI 77499",
      "CI 77499",
      "CI 77499",
      "ISONONYL ISONONANOATE",
    ],
    bad_ones: [],
  },
  {
    id: 31,
    imageUrl: "https://static.ewg.org/skindeep_images/6570/657043.jpg",
    field: "Foundation",
    name: "Beautycounter Tint Skin Hydrating Foundation, Sand",
    manufacturer: "Beautycounter",
    ingredients: [
      "CITRUS AURANTIUM DULCIS (ORANGE) OIL",
      "DIMETHICONE",
      "SODIUM BENZOATE",
      "ROSA DAMASCENA (ROSE) FLOWER OIL",
      "PROPANEDIOL",
      "GLYCERIN",
      "LECITHIN",
      "CITRUS AURANTIUM BERGAMIA (BERGAMOT) FRUIT OIL",
      "CI 77499",
      "CI 77499",
    ],
    bad_ones: [],
  },
  {
    id: 32,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/610224/original.",
    field: "Makeup Remover",
    name: "Jeffree Star Skin MAKE ME MELT MAKEUP REMOVING BALM",
    manufacturer: "Free Star",
    ingredients: [
      "CI 45410 (D&C RED NO. 27 OR 28) LAKE",
      "PHENOXYETHANOL",
      "ETHYLHEXYLGLYCERIN",
      "DECYL GLUCOSIDE",
      "CITRIC ACID",
      "TIN OXIDE",
      "ETHYLHEXYL PALMITATE",
      "CAPRYLIC/ CAPRIC TRIGLYCERIDE",
      "POLYETHYLENE",
      "POLYGLYCERYL-4 CAPRATE",
    ],
    bad_ones: [],
  },
  {
    id: 33,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/603376/original.",
    field: "Makeup Remover",
    name: "Madara Bi-Phase Makeup Remover",
    manufacturer: "Madara",
    ingredients: [
      "LACTIC ACID",
      "SODIUM BENZOATE",
      "GLYCERIN",
      "ANTHEMIS NOBILIS (CHAMOMILE) FLOWER EXTRACT",
      "CITRIC ACID",
      "POTASSIUM SORBATE",
      "ALOE BARBADENSIS (ALOE VERA) LEAF JUICE",
      "ISOAMYL LAURATE",
      "BUTYLENE GLYCOL",
      "WATER",
    ],
    bad_ones: [],
  },
  {
    id: 34,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/590630/original.",
    field: "Lip Balm",
    name: "Florence by Mills Oh Whale! Tinted Lip Balm, Guava and Lychee",
    manufacturer: "Florence by Mills Oh Whale!",
    ingredients: [
      "FD&C YELLOW NO. 5 (CI 19140) LAKE",
      "UNSPECIFIED FLAVOR",
      "ROSA CANINA (DOG ROSE) FRUIT OIL",
      "TOCOPHERYL ACETATE",
      "CI 15850 (D&C RED NO. 6 OR 7) LAKE",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "DIISOSTEARYL MALATE",
      "ETHYLENEDIAMINE / HYDROGENATED DIMER DILINOLEATE COPOLYMER BIS-DI-C14-18 ALKYL AMIDE",
      "OCTYLDODECANOL",
      "DIISOPROPYL DIMER DILINOLEATE",
    ],
    bad_ones: [],
  },
  {
    id: 35,
    imageUrl: "https://phorcys-static.ewg.org/image/contents/581657/original.",
    field: "Lip Balm",
    name: "Burts Bees Tinted Lip Balm, Daisy",
    manufacturer: "Burts Bees",
    ingredients: [
      "UNSPECIFIED FLAVOR",
      "RICINUS COMMUNIS (CASTOR) SEED OIL",
      "ALUMINA",
      "CI 77499",
      "CI 77499",
      "CI 77499",
      "COCOS NUCIFERA (COCONUT) OIL",
      "OLUS",
      "BEESWAX",
      "OLEA EUROPAEA (OLIVE) OIL",
    ],
    bad_ones: [],
  },
];
